### ISSUE TITLE
Basic example throws an error

### ISSUE THREAD

**Issue by dgrosbard11** [ryutok/mpl_axes_aligner#7]
If you try the basic example from the documentation on this project in a Jupyter notebook you get an error `AttributeError: module 'mpl_axes_aligner' has no attribute 'align'`

**Comment by herluc** [comment]
same here. __init__.py seems incomplete?

**Comment by herluc** [comment]
anyways great package, used the raw code in a project, works nice

**Comment by ryutok** [comment]
@dgrosbard11 @herluc 

I modified the __init__.py file and fixed the error.
Please update the mpl_axes_aligner to ver. 1.2.

Sorry for the late response.
Thank you for your cooperation.

**Comment by herluc** [comment]
fantastic, thanks!
